/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javafinal;


public class GirisEkrani extends javax.swing.JFrame {

    /**
     * Creates new form GirisEkrani
     */
    public GirisEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nasilOynanir = new javax.swing.JButton();
        cikis = new javax.swing.JButton();
        OynaButonu = new javax.swing.JButton();
        OynaButonu1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 640));
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setPreferredSize(new java.awt.Dimension(1000, 640));
        setSize(new java.awt.Dimension(1000, 640));
        getContentPane().setLayout(null);

        nasilOynanir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javafinal/icons8-info-100.png"))); // NOI18N
        nasilOynanir.setActionCommand("nasilOynanir");
        nasilOynanir.setBorderPainted(false);
        nasilOynanir.setContentAreaFilled(false);
        nasilOynanir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nasilOynanirActionPerformed(evt);
            }
        });
        getContentPane().add(nasilOynanir);
        nasilOynanir.setBounds(500, 290, 230, 110);

        cikis.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        cikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javafinal/icons8-exit-100 (1).png"))); // NOI18N
        cikis.setActionCommand("Cikis");
        cikis.setBorderPainted(false);
        cikis.setContentAreaFilled(false);
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });
        getContentPane().add(cikis);
        cikis.setBounds(510, 460, 240, 100);

        OynaButonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javafinal/output-onlinepngtools.png"))); // NOI18N
        OynaButonu.setBorderPainted(false);
        OynaButonu.setContentAreaFilled(false);
        OynaButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OynaButonuActionPerformed(evt);
            }
        });
        getContentPane().add(OynaButonu);
        OynaButonu.setBounds(110, 230, 490, 260);

        OynaButonu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javafinal/icons8-add-property-100.png"))); // NOI18N
        OynaButonu1.setBorderPainted(false);
        OynaButonu1.setContentAreaFilled(false);
        OynaButonu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OynaButonu1ActionPerformed(evt);
            }
        });
        getContentPane().add(OynaButonu1);
        OynaButonu1.setBounds(240, 450, 240, 110);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 130, 500, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javafinal/kelimeoyunu.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, -10, 880, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nasilOynanirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nasilOynanirActionPerformed
       new nasilOynanir().setVisible(true);
    }//GEN-LAST:event_nasilOynanirActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cikisActionPerformed

    private void OynaButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OynaButonuActionPerformed
        new KullaniciAdi().setVisible(true);
    }//GEN-LAST:event_OynaButonuActionPerformed

    private void OynaButonu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OynaButonu1ActionPerformed
       new soruEkle().setVisible(true);
    }//GEN-LAST:event_OynaButonu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OynaButonu;
    private javax.swing.JButton OynaButonu1;
    private javax.swing.JButton cikis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nasilOynanir;
    // End of variables declaration//GEN-END:variables
}
