/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javafinal;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


public class KullaniciAdi extends javax.swing.JFrame {
int kacHarfli=4;
    /**
     * Creates new form KullaniciAdi
     */
    public KullaniciAdi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        baslaButton = new javax.swing.JButton();
        arkaPlan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(617, 323));
        setMinimumSize(new java.awt.Dimension(617, 323));
        setSize(new java.awt.Dimension(617, 323));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Kullanıcı Adı Giriniz : ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 13, 309, 76);
        getContentPane().add(userName);
        userName.setBounds(333, 25, 247, 56);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Süreniz : 4 Dakika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 96, 309, 76);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Soru Sayısı : 14");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 179, 309, 76);

        baslaButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        baslaButton.setForeground(new java.awt.Color(51, 51, 51));
        baslaButton.setText("Başla");
        baslaButton.setToolTipText("");
        baslaButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        baslaButton.setContentAreaFilled(false);
        baslaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baslaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(baslaButton);
        baslaButton.setBounds(333, 189, 196, 66);

        arkaPlan.setBackground(new java.awt.Color(239, 235, 224));
        arkaPlan.setForeground(new java.awt.Color(239, 235, 224));
        arkaPlan.setOpaque(true);
        getContentPane().add(arkaPlan);
        arkaPlan.setBounds(1, 6, 620, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baslaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baslaButtonActionPerformed
         OyunArayuz a =new OyunArayuz(); 
         CreateFile b = new CreateFile();
         a.setVisible(true);
         this.setVisible(false);
         String KullaniciAdi=userName.getText();
        a.setUserNameLabel("Hoşgeldin, "+KullaniciAdi);
        a.baslangic();
        
    }//GEN-LAST:event_baslaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciAdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciAdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciAdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciAdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciAdi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel arkaPlan;
    private javax.swing.JButton baslaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
