/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javafinal;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;



public class OyunArayuz extends javax.swing.JFrame {
/**
 * 
     * Creates new form OyunArayuz
     */
    CreateFile Islem = new CreateFile();
    OyunBitis Final= new OyunBitis();
    public OyunArayuz() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        cevapVeriyorum = new javax.swing.JButton();
        cevapText = new javax.swing.JTextField();
        cevapLabel = new javax.swing.JLabel();
        soruLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        HarfAliyorum = new javax.swing.JButton();
        puanText = new javax.swing.JLabel();
        arkaPlan = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javafinal/5963160161361f10b45308f7.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1000, 640));
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setPreferredSize(new java.awt.Dimension(1000, 640));
        setSize(new java.awt.Dimension(1000, 640));
        getContentPane().setLayout(null);

        cevapVeriyorum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javafinal/output-onlinepngtools.png"))); // NOI18N
        cevapVeriyorum.setBorder(null);
        cevapVeriyorum.setBorderPainted(false);
        cevapVeriyorum.setContentAreaFilled(false);
        cevapVeriyorum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cevapVeriyorum.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cevapVeriyorum.setDefaultCapable(false);
        cevapVeriyorum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cevapVeriyorumActionPerformed(evt);
            }
        });
        getContentPane().add(cevapVeriyorum);
        cevapVeriyorum.setBounds(450, 410, 140, 140);

        cevapText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cevapText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cevapTextActionPerformed(evt);
            }
        });
        getContentPane().add(cevapText);
        cevapText.setBounds(280, 300, 280, 60);

        cevapLabel.setFont(new java.awt.Font("Times New Roman", 1, 35)); // NOI18N
        getContentPane().add(cevapLabel);
        cevapLabel.setBounds(80, 370, 270, 47);

        soruLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        soruLabel.setForeground(new java.awt.Color(51, 51, 51));
        soruLabel.setText("KELİME:");
        getContentPane().add(soruLabel);
        soruLabel.setBounds(30, 190, 870, 60);

        userNameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(userNameLabel);
        userNameLabel.setBounds(20, 40, 260, 70);

        HarfAliyorum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        HarfAliyorum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javafinal/icons8-plus-160.png"))); // NOI18N
        HarfAliyorum.setBorder(null);
        HarfAliyorum.setBorderPainted(false);
        HarfAliyorum.setContentAreaFilled(false);
        HarfAliyorum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HarfAliyorum.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        HarfAliyorum.setDefaultCapable(false);
        HarfAliyorum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HarfAliyorumActionPerformed(evt);
            }
        });
        getContentPane().add(HarfAliyorum);
        HarfAliyorum.setBounds(230, 380, 210, 180);

        puanText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        puanText.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(puanText);
        puanText.setBounds(300, 30, 270, 90);

        arkaPlan.setBackground(new java.awt.Color(239, 235, 224));
        arkaPlan.setForeground(new java.awt.Color(239, 235, 224));
        arkaPlan.setOpaque(true);
        getContentPane().add(arkaPlan);
        arkaPlan.setBounds(1, 6, 1030, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 int soruCounter=1;
 int puan=0;
 int puan1=0;
 String tutmaç;
 
 
    private void cevapVeriyorumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cevapVeriyorumActionPerformed
    //cevapKontrol(cevapText.getText());
    soruCounter++;
    Islem.sayac=0;
    if(cevapText.getText().toLowerCase().equals(Islem.part[1])){
        puan=puan+Islem.kazanılacakPuan;
        tutmaç=String.valueOf(puan);
        puanText.setText("Puanınız : "+tutmaç);           
    }
    else{
        puan=puan-Islem.kazanılacakPuan;
        tutmaç=String.valueOf(puan);
        puanText.setText("Puanınız : "+tutmaç); 
    }
    
    getirSoru(soruCounter);
     
    }//GEN-LAST:event_cevapVeriyorumActionPerformed
    public  void  baslangic(){
        getirSoru(soruCounter);
        tutmaç=String.valueOf(puan);
        puanText.setText("Puanınız : "+tutmaç);
        
       
    }
    private void cevapTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cevapTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cevapTextActionPerformed

    private void HarfAliyorumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HarfAliyorumActionPerformed
        try {
            cevapAlabilirMiyim(cevapLabel);
        } catch (IOException ex) {
            Logger.getLogger(OyunArayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_HarfAliyorumActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OyunArayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OyunArayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OyunArayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OyunArayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OyunArayuz().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HarfAliyorum;
    public javax.swing.JLabel arkaPlan;
    public javax.swing.JLabel cevapLabel;
    private javax.swing.JTextField cevapText;
    private javax.swing.JButton cevapVeriyorum;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel puanText;
    public javax.swing.JLabel soruLabel;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables

    public void setUserNameLabel(String userName) {
        this.userNameLabel.setText(userName);
    }
    
    public void getirSoru(int soruCounter){
         
        switch(soruCounter){
        case 1: 
    {
        try {
            Islem.oku(4,soruLabel,cevapLabel);
        } catch (IOException ex) {
            Logger.getLogger(OyunArayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
        Islem.kazanılacakPuan=400;
    }
        break;
        case 2:  {
        try {
            Islem.oku(4,soruLabel,cevapLabel);
        } catch (IOException ex) {
            Logger.getLogger(OyunArayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
        Islem.kazanılacakPuan=400;
    }
         break;
        case 3:  {
        try {
            Islem.oku(5,soruLabel,cevapLabel);
        } catch (IOException ex) {
            Logger.getLogger(OyunArayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
        Islem.kazanılacakPuan=500;
    }
         break;
        case 4:  {
        try {
            Islem.oku(5,soruLabel,cevapLabel);
        } catch (IOException ex) {
            Logger.getLogger(OyunArayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
        Islem.kazanılacakPuan=500;
    }
         break;
        case 5:  {
        try {
            Islem.oku(6,soruLabel,cevapLabel);
        } catch (IOException ex) {
            Logger.getLogger(OyunArayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
        Islem.kazanılacakPuan=600;
    }
         break;
        case 6:  {
        try {
            Islem.oku(6,soruLabel,cevapLabel);
        } catch (IOException ex) {
            Logger.getLogger(OyunArayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
        Islem.kazanılacakPuan=600;
    }
         break;
        case 7:  {
        try {
            Islem.oku(7,soruLabel,cevapLabel);
        } catch (IOException ex) {
            Logger.getLogger(OyunArayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
        Islem.kazanılacakPuan=700;
    }
         break;
        case 8:  {
        try {
            Islem.oku(7,soruLabel,cevapLabel);
        } catch (IOException ex) {
            Logger.getLogger(OyunArayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
        Islem.kazanılacakPuan=700;
    }
         break;
        case 9:  {
        try {
            Islem.oku(8,soruLabel,cevapLabel);
        } catch (IOException ex) {
            Logger.getLogger(OyunArayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
        Islem.kazanılacakPuan=800;
    }
         break;
        case 10:  {
        try {
            Islem.oku(8,soruLabel,cevapLabel);
        } catch (IOException ex) {
            Logger.getLogger(OyunArayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
        Islem.kazanılacakPuan=800;
    }
         break;
        case 11:  {
        try {
            Islem.oku(9,soruLabel,cevapLabel);
        } catch (IOException ex) {
            Logger.getLogger(OyunArayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
        Islem.kazanılacakPuan=900;
    }
         break;
        case 12:  {
        try {
            Islem.oku(9,soruLabel,cevapLabel);
        } catch (IOException ex) {
            Logger.getLogger(OyunArayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
        Islem.kazanılacakPuan=900;
    }
         break;
        case 13:  {
        try {
            Islem.oku(10,soruLabel,cevapLabel);
        } catch (IOException ex) {
            Logger.getLogger(OyunArayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
        Islem.kazanılacakPuan=1000;
    }
         break;
        case 14: { 
        try {
            Islem.oku(10,soruLabel,cevapLabel);
        } catch (IOException ex) {
            Logger.getLogger(OyunArayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
        Islem.kazanılacakPuan=1000;
    }
        break;
        case 15:
        {
            this.setVisible(false);
            Final.setVisible(true);
           Final.OyunBitti.setText("Oyun Bitmiştir");
           Final.FinalPuan.setText("Puanınız : "+tutmaç);
        }
        
    }
    }
    public void cevapAlabilirMiyim(JLabel cevap) throws IOException{
     Islem.harfAlim(cevap);
    }
}
